# Generated by Django 5.2.3 on 2025-06-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_item_comment_bid_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(default='https://images.vexels.com/media/users/3/145641/isolated/preview/30bc99162bca69bdbd27451ceeef8848-earth-stone-illustration.png'),
        ),
    ]
