# Generated by Django 5.2.3 on 2025-06-27 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_catagory_item_category_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
