# Generated by Django 5.2.3 on 2025-06-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
