# Generated by Django 5.2.3 on 2025-06-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airport_flight_delete_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='flights.flight')),
            ],
        ),
    ]
